// Generated by blog/_quiz.py. Do not edit by hand.
module.exports = {
  "pt": {
    "path": "/diagnostico/",
    "ui": {
      "kicker": "Diagnóstico gratuito",
      "title": "O seu site está a trabalhar por si?",
      "intro": "Responda a 9 perguntas rápidas e descubra, em 2 minutos, o que está a funcionar, o que pode estar a afastar clientes e qual o próximo passo que faz mais sentido para o seu negócio.",
      "start": "Começar o diagnóstico",
      "note": "Sem registo. Resultado imediato.",
      "progress": "Pergunta {n} de {t}",
      "back": "Voltar",
      "urlLabel": "Opcional",
      "urlQ": "Qual é o endereço do seu site?",
      "urlPlaceholder": "exemplo.pt",
      "urlNext": "Continuar",
      "urlSkip": "Prefiro não dizer",
      "urlInvalid": "Confirme o endereço (por exemplo, exemplo.pt).",
      "resultKicker": "O seu resultado",
      "scoreLabel": "Saúde do site",
      "weakTitle": "Onde o site está a perder",
      "noWeak": "Não encontrámos pontos fracos importantes. O site cumpre bem o que se espera dele.",
      "planTitle": "O próximo passo recomendado",
      "mailTitle": "Saiba exatamente como corrigir cada ponto",
      "mailTitleOne": "Saiba exatamente como corrigir este ponto",
      "mailTextMinor": "O resumo acima mostra o que ainda pode melhorar. O relatório completo mostra como. Saiba que passos concretos pode dar já para tirar ainda mais partido do site. Inclui ainda o guia {guide}.",
      "mailText": "O resumo acima mostra onde o site está a falhar. O relatório completo mostra como resolver. Saiba que passos concretos pode dar já para ter resultados mais depressa. Inclui ainda o guia {guide}.",
      "mailGuide": "8 sinais de que o seu site está a afastar clientes",
      "mailTitleGood": "Receba o resultado e o guia por email",
      "mailTextGood": "Guarde o seu diagnóstico e receba o guia {guide}, para o continuar a manter em boa forma no futuro.",
      "mailSendGood": "Enviar",
      "mailTextNoSite": "Guarde o seu diagnóstico e receba o guia {guide}, para criar o seu site sem cair nos erros mais comuns.",
      "mailNoteGood": "Os seus dados servem apenas para enviar o resultado e o guia. Política de Privacidade",
      "mailPlaceholder": "O seu email",
      "mailSend": "Receber o relatório",
      "mailOk": "Enviado! Veja a sua caixa de entrada nos próximos minutos.",
      "mailFail": "Não foi possível enviar agora. Pode escrever para info@mariana-marcelino.com.",
      "mailNote": "Os seus dados servem apenas para enviar o relatório. Política de Privacidade",
      "restart": "Refazer o diagnóstico",
      "noSiteTitle": "Começar do zero",
      "noSiteText": "Ainda não tem site, por isso não há nada a corrigir: há tudo por construir, e da forma certa desde o início."
    },
    "questions": [
      {
        "id": "q1",
        "q": "Já tem site?",
        "options": [
          {
            "t": "Sim",
            "p": 0
          },
          {
            "t": "Ainda não",
            "p": 0,
            "skip": true
          }
        ]
      },
      {
        "id": "q2",
        "cat": "image",
        "q": "Há quanto tempo o site foi feito ou renovado?",
        "options": [
          {
            "t": "Há menos de 2 anos",
            "p": 0
          },
          {
            "t": "Entre 2 e 4 anos",
            "p": 1
          },
          {
            "t": "Há mais de 4 anos, ou não sei",
            "p": 2
          }
        ]
      },
      {
        "id": "q3",
        "cat": "image",
        "q": "Como se comporta o site no telemóvel?",
        "options": [
          {
            "t": "Funciona e fica bem",
            "p": 0
          },
          {
            "t": "Funciona, mas não é ideal",
            "p": 1
          },
          {
            "t": "É difícil de ler ou de usar",
            "p": 2
          }
        ]
      },
      {
        "id": "q4",
        "cat": "image",
        "q": "O site transmite a imagem atual do seu negócio?",
        "options": [
          {
            "t": "Sim, representa-o bem",
            "p": 0
          },
          {
            "t": "Mais ou menos",
            "p": 1
          },
          {
            "t": "Não, ficou para trás",
            "p": 2
          }
        ]
      },
      {
        "id": "q5",
        "cat": "reach",
        "q": "Quando alguém procura o seu serviço na sua zona, o seu negócio aparece no Google?",
        "options": [
          {
            "t": "Sim, entre os primeiros resultados",
            "p": 0
          },
          {
            "t": "Sim, mas mais abaixo nos resultados",
            "p": 1
          },
          {
            "t": "Não, ou não sei",
            "p": 2
          }
        ]
      },
      {
        "id": "q6",
        "cat": "reach",
        "q": "E nas ferramentas de IA, como o ChatGPT?",
        "options": [
          {
            "t": "Sim, já aparece nas respostas",
            "p": 0
          },
          {
            "t": "Nunca experimentei ver",
            "p": 1
          },
          {
            "t": "Não aparece",
            "p": 2
          }
        ]
      },
      {
        "id": "q7",
        "cat": "leads",
        "q": "Quantos pedidos de contacto ou marcações chegam pelo site?",
        "options": [
          {
            "t": "Vários por mês",
            "p": 0
          },
          {
            "t": "Poucos",
            "p": 1
          },
          {
            "t": "Quase nenhuns, ou não sei",
            "p": 2
          }
        ]
      },
      {
        "id": "q8",
        "cat": "leads",
        "q": "Quem visita percebe logo o que faz e como o contactar?",
        "options": [
          {
            "t": "Sim, em poucos segundos",
            "p": 0
          },
          {
            "t": "Tem de procurar um pouco",
            "p": 1
          },
          {
            "t": "Não tenho a certeza",
            "p": 2
          }
        ]
      },
      {
        "id": "q9",
        "goal": true,
        "q": "O que é mais importante para si agora?",
        "options": [
          {
            "t": "Ter um site com uma imagem à altura do negócio",
            "g": "image"
          },
          {
            "t": "Ser encontrado por mais pessoas",
            "g": "reach"
          },
          {
            "t": "Receber mais contactos e marcações",
            "g": "leads"
          },
          {
            "t": "Ainda estou a explorar",
            "g": "explore"
          }
        ]
      }
    ],
    "bands": [
      {
        "min": 80,
        "title": "Em boa forma",
        "text": "O seu site está a fazer bem o essencial. Há apenas pequenos ajustes que podem fazê-lo render ainda mais."
      },
      {
        "min": 50,
        "title": "Com margem para crescer",
        "text": "O site cumpre, mas está a deixar contactos pelo caminho em alguns pontos."
      },
      {
        "min": 0,
        "title": "A perder oportunidades",
        "text": "Há vários pontos em que o site está a afastar quem o procura. A boa notícia: são todos corrigíveis."
      }
    ],
    "weak": {
      "q2": {
        "title": "Desatualizado",
        "line": "Um site com vários anos transmite que o negócio também parou no tempo.",
        "todo": "Renove o design e os conteúdos: imagens atuais, textos que refletem o que faz hoje e um aspeto à altura do negócio."
      },
      "q3": {
        "title": "Telemóvel",
        "line": "A maioria das visitas vem do telemóvel. Se lá falha, a visita perde-se.",
        "todo": "Abra o site no telemóvel e tente encontrar o contacto e marcar algo. Tudo deve ser legível sem zoom e clicável com o polegar."
      },
      "q4": {
        "title": "Imagem",
        "line": "Quem visita julga o negócio pelo site em segundos. Hoje, o site não está à sua altura.",
        "todo": "Alinhe o site com a forma como se posiciona: tipografia, fotografias reais e uma mensagem clara no topo da página."
      },
      "q5": {
        "title": "Google",
        "line": "Se não aparece quando procuram o seu serviço na zona, os concorrentes ficam com esses clientes.",
        "todo": "Complete o Perfil da Empresa no Google, peça avaliações e garanta que cada página tem título, descrição e o serviço e a zona bem claros."
      },
      "q6": {
        "title": "IA",
        "line": "Cada vez mais pessoas pedem recomendações ao ChatGPT. Um site preparado para isso passa a ser citado.",
        "todo": "Responda de forma direta às perguntas que os seus clientes fazem, deixe claro o que faz, para quem e onde, e permita o acesso dos robôs das ferramentas de IA."
      },
      "q7": {
        "title": "Contactos",
        "line": "Visitas sem contactos significam que o site não está a guiar as pessoas até ao passo seguinte.",
        "todo": "Dê um próximo passo claro em cada página (marcar, pedir orçamento, falar no WhatsApp) e reduza os campos dos formulários ao essencial."
      },
      "q8": {
        "title": "Clareza",
        "line": "Se não fica claro em segundos o que faz e como o contactar, a maioria sai sem procurar.",
        "todo": "No topo da página: o que faz, para quem e um botão de contacto visível. Teste com alguém que não conheça o negócio."
      }
    },
    "plans": {
      "engine": {
        "name": "Motor de Contactos",
        "line": "O seu site precisa de mais do que uma nova imagem: precisa também de ser encontrado e de transformar visitas em contactos.",
        "lineNoSite": "Começar do zero é a melhor altura para fazer um site que trabalha pelo negócio desde o primeiro dia.",
        "cta": {
          "t": "Marcar chamada",
          "href": "https://calendly.com/marianacmarcelino/30min"
        },
        "cta2": {
          "t": "Ver o que inclui",
          "href": "/#motor-de-contactos"
        }
      },
      "visual": {
        "name": "Nova Imagem",
        "line": "A estrutura serve, mas a imagem está a afastar quem visita. Um novo design resolve o essencial.",
        "also": "Se também quiser ser mais encontrado e receber mais contactos, o Motor de Contactos resolve essa parte.",
        "cta": {
          "t": "Pedir redesign gratuito",
          "href": "/#pedir-redesign"
        },
        "cta2": {
          "t": "Ver o que inclui",
          "href": "/#nova-imagem"
        }
      },
      "call": {
        "name": "Uma conversa sem compromisso",
        "line": "O seu site está em boa forma. Numa chamada de 30 minutos, vemos juntos o que ainda pode ser melhorado.",
        "cta": {
          "t": "Marcar chamada",
          "href": "https://calendly.com/marianacmarcelino/30min"
        },
        "cta2": {
          "t": "Ver os planos",
          "href": "/#solutions"
        }
      },
      "free": {
        "name": "Redesign da Homepage (gratuito)",
        "line": "Como ainda está a explorar, veja, sem compromisso, como o seu site pode ficar.",
        "cta": {
          "t": "Pedir redesign gratuito",
          "href": "/#pedir-redesign"
        },
        "cta2": {
          "t": "Ver o que inclui",
          "href": "/#free"
        }
      }
    },
    "report": {
      "subject": "O seu diagnóstico: {score}/100 · {band}",
      "subjectSite": "Diagnóstico de {site}: {score}/100 · {band}",
      "subjectNoSite": "O seu diagnóstico: começar do zero",
      "intro": "Obrigada por fazer o diagnóstico. Aqui está o seu resultado completo, com cada ponto explicado e por onde começar.",
      "introNoSite": "Obrigada por fazer o diagnóstico. Como ainda não tem site, não há nada a corrigir: há tudo por construir, e da forma certa desde o início.",
      "introGood": "Obrigada por fazer o diagnóstico. O seu site está em boa forma, e aqui fica o resultado para guardar, com o guia para o manter assim.",
      "scoreLine": "Saúde do site: {score}/100 · {band}",
      "weakTitle": "Pontos a melhorar",
      "doLabel": "O que fazer: ",
      "planTitle": "Próximo passo recomendado",
      "guide": "E, como prometido, o guia completo: ",
      "guideNoSite": "E, como prometido, aqui fica o guia completo ",
      "guideAfterNoSite": " – para criar o seu site sem cair nos erros mais comuns.",
      "guideLink": "Oito sinais de que o seu site está a afastar clientes",
      "guideHref": "https://www.mariana-marcelino.com/assets/guia-8-sinais.pdf",
      "free": "A chamada é gratuita e sem compromisso – serve para olharmos juntos para o seu caso."
    }
  },
  "en": {
    "path": "/en/diagnosis/",
    "ui": {
      "kicker": "Free diagnosis",
      "title": "Is your website working for you?",
      "intro": "Answer 9 quick questions and, in 2 minutes, find out what's working, what might be driving clients away and the best next step for your business.",
      "start": "Start the diagnosis",
      "note": "No sign-up. Instant result.",
      "progress": "Question {n} of {t}",
      "back": "Back",
      "urlLabel": "Optional",
      "urlQ": "What's your website address?",
      "urlPlaceholder": "example.com",
      "urlNext": "Continue",
      "urlSkip": "I'd rather not say",
      "urlInvalid": "Check the address (for example, example.com).",
      "resultKicker": "Your result",
      "scoreLabel": "Website health",
      "weakTitle": "Where your website is falling short",
      "noWeak": "No major weak spots. Your website is doing its job.",
      "planTitle": "Recommended next step",
      "mailTitle": "Find out exactly how to fix each one",
      "mailTitleOne": "Find out exactly how to fix it",
      "mailTextMinor": "The summary above shows what could still be better. The full report shows you how, with concrete steps you can take right away to get even more from your website. It also includes the guide {guide}.",
      "mailText": "The summary above shows where your website is falling short. The full report shows you how to fix it, with concrete steps you can take right away to see results sooner. It also includes the guide {guide}.",
      "mailGuide": "8 signs your website is driving clients away",
      "mailTitleGood": "Get your result and the guide by email",
      "mailTextGood": "Save your diagnosis and get the guide {guide} to keep your website in good shape.",
      "mailSendGood": "Send",
      "mailTextNoSite": "Save your diagnosis and get the guide {guide} to build your website without the most common mistakes.",
      "mailNoteGood": "Your details are only used to send the result and the guide. Privacy Policy",
      "mailPlaceholder": "Your email",
      "mailSend": "Get the report",
      "mailOk": "Sent! Check your inbox in the next few minutes.",
      "mailFail": "Something went wrong and it couldn't be sent. You can email info@mariana-marcelino.com instead.",
      "mailNote": "Your details are only used to send the report. Privacy Policy",
      "restart": "Take the diagnosis again",
      "noSiteTitle": "Starting from scratch",
      "noSiteText": "You don't have a website yet, so there's nothing to fix, just a website to build the right way from day one."
    },
    "questions": [
      {
        "id": "q1",
        "q": "Do you have a website?",
        "options": [
          {
            "t": "Yes",
            "p": 0
          },
          {
            "t": "Not yet",
            "p": 0,
            "skip": true
          }
        ]
      },
      {
        "id": "q2",
        "cat": "image",
        "q": "When was your website built or last redesigned?",
        "options": [
          {
            "t": "Less than 2 years ago",
            "p": 0
          },
          {
            "t": "Between 2 and 4 years ago",
            "p": 1
          },
          {
            "t": "More than 4 years ago, or I don't know",
            "p": 2
          }
        ]
      },
      {
        "id": "q3",
        "cat": "image",
        "q": "How does your website work on a phone?",
        "options": [
          {
            "t": "It works and looks good",
            "p": 0
          },
          {
            "t": "It works, but it's not ideal",
            "p": 1
          },
          {
            "t": "It's hard to read or use",
            "p": 2
          }
        ]
      },
      {
        "id": "q4",
        "cat": "image",
        "q": "Does your website reflect your business as it is today?",
        "options": [
          {
            "t": "Yes, it represents it well",
            "p": 0
          },
          {
            "t": "More or less",
            "p": 1
          },
          {
            "t": "No, it's fallen behind",
            "p": 2
          }
        ]
      },
      {
        "id": "q5",
        "cat": "reach",
        "q": "When someone searches for your service in your area, does your business show up on Google?",
        "options": [
          {
            "t": "Yes, among the top results",
            "p": 0
          },
          {
            "t": "Yes, but further down the results",
            "p": 1
          },
          {
            "t": "No, or I don't know",
            "p": 2
          }
        ]
      },
      {
        "id": "q6",
        "cat": "reach",
        "q": "And in AI tools like ChatGPT?",
        "options": [
          {
            "t": "Yes, it already shows up in answers",
            "p": 0
          },
          {
            "t": "I've never checked",
            "p": 1
          },
          {
            "t": "It doesn't show up",
            "p": 2
          }
        ]
      },
      {
        "id": "q7",
        "cat": "leads",
        "q": "How many enquiries or bookings come through your website?",
        "options": [
          {
            "t": "Several a month",
            "p": 0
          },
          {
            "t": "A few",
            "p": 1
          },
          {
            "t": "Hardly any, or I don't know",
            "p": 2
          }
        ]
      },
      {
        "id": "q8",
        "cat": "leads",
        "q": "Can visitors tell straight away what you do and how to contact you?",
        "options": [
          {
            "t": "Yes, within seconds",
            "p": 0
          },
          {
            "t": "They have to look around a bit",
            "p": 1
          },
          {
            "t": "I'm not sure",
            "p": 2
          }
        ]
      },
      {
        "id": "q9",
        "goal": true,
        "q": "What matters most to you right now?",
        "options": [
          {
            "t": "A website that looks as good as the business",
            "g": "image"
          },
          {
            "t": "Being found by more people",
            "g": "reach"
          },
          {
            "t": "Getting more enquiries and bookings",
            "g": "leads"
          },
          {
            "t": "I'm still exploring",
            "g": "explore"
          }
        ]
      }
    ],
    "bands": [
      {
        "min": 80,
        "title": "In good shape",
        "text": "Your website gets the essentials right. There are just a few small tweaks that could make it work even harder."
      },
      {
        "min": 50,
        "title": "Room to grow",
        "text": "Your website does the job, but it's losing enquiries in a few places."
      },
      {
        "min": 0,
        "title": "Missing opportunities",
        "text": "Your website is turning away people who are looking for you. The good news: it's all fixable."
      }
    ],
    "weak": {
      "q2": {
        "title": "Outdated",
        "line": "A website that's several years old suggests the business has stood still too.",
        "todo": "Refresh the design and content: current images, copy that reflects what you do today and a look that matches the business."
      },
      "q3": {
        "title": "Mobile",
        "line": "Most visits come from phones. If it fails there, the visit is lost.",
        "todo": "Open the website on your phone and try to find the contact details and book something. Everything should be readable without zooming and tappable with a thumb."
      },
      "q4": {
        "title": "Image",
        "line": "Visitors judge the business by its website in seconds. Right now, it isn't doing it justice.",
        "todo": "Bring the website in line with how you want to be seen: typography, real photos and a clear message at the top of the page."
      },
      "q5": {
        "title": "Google",
        "line": "If you don't show up when people search for your service locally, competitors get those clients.",
        "todo": "Complete your Google Business Profile, ask for reviews and make sure every page has a clear title, description, service and area."
      },
      "q6": {
        "title": "AI",
        "line": "More and more people ask ChatGPT for recommendations. Websites that are ready for it get cited.",
        "todo": "Answer your clients' questions directly, make clear what you do, for whom and where, and allow AI tools' crawlers to access the site."
      },
      "q7": {
        "title": "Enquiries",
        "line": "Visitors but no enquiries means the website isn't guiding people to the next step.",
        "todo": "Give every page a clear next step (book, ask for a quote, chat on WhatsApp) and cut form fields down to the essentials."
      },
      "q8": {
        "title": "Clarity",
        "line": "If it isn't clear within seconds what you do and how to reach you, most people leave without looking.",
        "todo": "At the top of the page: what you do, for whom and a visible contact button. Test it with someone who doesn't know the business."
      }
    },
    "plans": {
      "engine": {
        "name": "Enquiry Engine",
        "line": "Your website needs more than a new look: it also needs to be found and to turn visits into enquiries.",
        "lineNoSite": "Starting from scratch is the best moment to build a website that works for your business from day one.",
        "cta": {
          "t": "Book a call",
          "href": "https://calendly.com/marianacmarcelino/30min"
        },
        "cta2": {
          "t": "See what's included",
          "href": "/en/#motor-de-contactos"
        }
      },
      "visual": {
        "name": "Fresh Look",
        "line": "The structure works, but the look is turning visitors away. A new design fixes the essentials.",
        "also": "If you'd also like to be found by more people and get more enquiries, the Enquiry Engine covers that too.",
        "cta": {
          "t": "Request a free redesign",
          "href": "/en/#pedir-redesign"
        },
        "cta2": {
          "t": "See what's included",
          "href": "/en/#nova-imagem"
        }
      },
      "call": {
        "name": "A no-strings chat",
        "line": "Your website is in good shape. In a 30-minute call, we'll look together at what could still be improved.",
        "cta": {
          "t": "Book a call",
          "href": "https://calendly.com/marianacmarcelino/30min"
        },
        "cta2": {
          "t": "See the plans",
          "href": "/en/#solutions"
        }
      },
      "free": {
        "name": "Homepage Redesign (free)",
        "line": "Since you're still exploring, see what your website could look like, with no commitment.",
        "cta": {
          "t": "Request a free redesign",
          "href": "/en/#pedir-redesign"
        },
        "cta2": {
          "t": "See what's included",
          "href": "/en/#free"
        }
      }
    },
    "report": {
      "subject": "Your diagnosis: {score}/100 · {band}",
      "subjectSite": "Diagnosis for {site}: {score}/100 · {band}",
      "subjectNoSite": "Your diagnosis: starting from scratch",
      "intro": "Thanks for taking the diagnosis. Here's your full result, with each point explained and where to start.",
      "introNoSite": "Thanks for taking the diagnosis. You don't have a website yet, so there's nothing to fix, just a website to build the right way from day one.",
      "introGood": "Thanks for taking the diagnosis. Your website is in good shape: here's your result, plus the guide to help keep it that way.",
      "scoreLine": "Website health: {score}/100 · {band}",
      "weakTitle": "Points to improve",
      "doLabel": "What to do: ",
      "planTitle": "Recommended next step",
      "guide": "And, as promised, the full guide: ",
      "guideNoSite": "And, as promised, here's the full guide ",
      "guideAfterNoSite": " – to build your website without the most common mistakes.",
      "guideLink": "Eight signs your website is driving clients away",
      "guideHref": "https://www.mariana-marcelino.com/assets/guide-8-signs.pdf",
      "free": "The call is free, with no commitment – a chance to look at your situation together."
    }
  }
};
